-- MySQL Script generated by MySQL Workbench
-- Thu Apr 18 11:25:25 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8 ;
USE `project` ;

-- -----------------------------------------------------
-- Table `project`.`EMPLOYEE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`EMPLOYEE` ;

CREATE TABLE IF NOT EXISTS `project`.`EMPLOYEE` (
  `EmployeeID` INT NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Airline` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`EmployeeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`CUSTOMERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`CUSTOMERS` ;

CREATE TABLE IF NOT EXISTS `project`.`CUSTOMERS` (
  `AccountID` INT NOT NULL,
  `RewardPoints` INT NULL,
  `Email` VARCHAR(45) NULL,
  `Address` VARCHAR(100) NULL,
  `Name` VARCHAR(45) NULL,
  `numChildren` INT NULL,
  `Citizenship` VARCHAR(45) NULL,
  `TSAPreCheck` VARCHAR(5) NULL,
  `SSN` VARCHAR(12) NULL,
  `CreditCard` VARCHAR(20) NULL,
  `CCExpirationDate` VARCHAR(40) NULL,
  `CCSecurityCode` VARCHAR(5) NULL,
  `Birthdate` VARCHAR(40) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`AccountID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`FLIGHT_INFORMATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`FLIGHT_INFORMATION` ;

CREATE TABLE IF NOT EXISTS `project`.`FLIGHT_INFORMATION` (
  `FlightID` INT NOT NULL,
  `Airline` VARCHAR(45) NULL,
  `numBags` INT NULL,
  `ArrivalTime` TIMESTAMP NULL,
  `DepartureTime` TIMESTAMP NULL,
  `Price` DOUBLE NULL,
  `Terminal` VARCHAR(2) NULL,
  `FlightStatus` VARCHAR(45) NULL,
  `StartingCity` VARCHAR(45) NULL,
  `EndCity` VARCHAR(45) NULL,
  `StartingGate` VARCHAR(45) NULL,
  `EndingGate` VARCHAR(45) NULL,
  `SeatClass` VARCHAR(45) NULL,
  PRIMARY KEY (`FlightID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`PLANE_INFORMATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`PLANE_INFORMATION` ;

CREATE TABLE IF NOT EXISTS `project`.`PLANE_INFORMATION` (
  `AircraftModel` VARCHAR(45) NOT NULL,
  `MaxLoadBaggage` INT NULL,
  `PlaneAge` INT NULL,
  `TypeOfSeating` CHAR NULL,
  `FuelCapacity` INT NULL,
  PRIMARY KEY (`AircraftModel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`FLIGHT_PERKS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`FLIGHT_PERKS` ;

CREATE TABLE IF NOT EXISTS `project`.`FLIGHT_PERKS` (
  `AccountID` INT NOT NULL,
  `Beverages` VARCHAR(45) NULL,
  `LegSpace` VARCHAR(45) NULL,
  `Entertainment` VARCHAR(45) NULL,
  `FlightID` INT NOT NULL,
  PRIMARY KEY (`AccountID`, `FlightID`),
  INDEX `FlightID_idx` (`FlightID` ASC) VISIBLE,
  CONSTRAINT `AccountID2`
    FOREIGN KEY (`AccountID`)
    REFERENCES `project`.`CUSTOMERS` (`AccountID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FlightID2`
    FOREIGN KEY (`FlightID`)
    REFERENCES `project`.`FLIGHT_INFORMATION` (`FlightID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`FLIES_ON`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`FLIES_ON` ;

CREATE TABLE IF NOT EXISTS `project`.`FLIES_ON` (
  `AccountID` INT NOT NULL,
  `FlightID` INT NOT NULL,
  PRIMARY KEY (`AccountID`, `FlightID`),
  INDEX `FlightID_idx` (`FlightID` ASC) VISIBLE,
  CONSTRAINT `AccountID1`
    FOREIGN KEY (`AccountID`)
    REFERENCES `project`.`CUSTOMERS` (`AccountID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FlightID1`
    FOREIGN KEY (`FlightID`)
    REFERENCES `project`.`FLIGHT_INFORMATION` (`FlightID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`FLIGHT_PLANE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`FLIGHT_PLANE` ;

CREATE TABLE IF NOT EXISTS `project`.`FLIGHT_PLANE` (
  `FlightID` INT NOT NULL,
  `AircraftModel` VARCHAR(45) NULL,
  PRIMARY KEY (`FlightID`),
  INDEX `AircraftModel_idx` (`AircraftModel` ASC) VISIBLE,
  CONSTRAINT `FlightID3`
    FOREIGN KEY (`FlightID`)
    REFERENCES `project`.`FLIGHT_INFORMATION` (`FlightID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `AircraftModel3`
    FOREIGN KEY (`AircraftModel`)
    REFERENCES `project`.`PLANE_INFORMATION` (`AircraftModel`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`MANAGES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`MANAGES` ;

CREATE TABLE IF NOT EXISTS `project`.`MANAGES` (
  `EmployeeID` INT NOT NULL,
  `FlightID` INT NOT NULL,
  PRIMARY KEY (`EmployeeID`, `FlightID`),
  INDEX `FlightID_idx` (`FlightID` ASC) VISIBLE,
  CONSTRAINT `EmployeeID4`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `project`.`EMPLOYEE` (`EmployeeID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FlightID4`
    FOREIGN KEY (`FlightID`)
    REFERENCES `project`.`FLIGHT_INFORMATION` (`FlightID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
